# Generated by Django 4.2.3 on 2023-07-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='chosen_time',
            field=models.DateTimeField(),
        ),
    ]
