# Generated by Django 4.2.3 on 2023-07-24 16:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
