# Generated by Django 4.2.3 on 2023-07-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_appointment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
